import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import "bootstrap-italia/dist/css/bootstrap-italia.min.css";


import React from "react"; 
import Script from "next/script"; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
          {children}
        <Footer />
      </body>
      <Script          
         src="bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js"        
      />   
    </html>
  )
}
